/*
更新测试数据时间
*/
delimiter $ 
drop procedure if exists Proc_HandleTestData $
create procedure Proc_HandleTestData() 
begin
    -- 插件-待安排的寄样
    Update SendSamples Set Deadline=DATE_ADD(curdate(),INTERVAL 3 DAY),SendSampleStatus = '待安排' Where TNTNo='SS1808001';
    Update SendSamples Set Deadline=DATE_ADD(curdate(),INTERVAL 10 DAY),SendSampleStatus = '待安排' Where TNTNo='SS1808002';
    Update SendSamples Set Deadline=DATE_ADD(curdate(),INTERVAL 14 DAY),SendSampleStatus = '待安排' Where TNTNo='SS1808003';

    -- 插件-处理中的报价
    Update Quotations Set InquiryDate=curdate(),QuotationStatus = '处理中' Where QuotationNo='QT1808001';
    Update Quotations Set InquiryDate=curdate(),QuotationStatus = '处理中' Where QuotationNo='QT1808002';
    Update Quotations Set InquiryDate=DATE_ADD(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) DAY),INTERVAL 3 DAY),QuotationStatus = '处理中' Where QuotationNo='QT1808003';
    Update Quotations Set InquiryDate=DATE_ADD(DATE_ADD(curdate(),INTERVAL -day(curdate())+1 day),INTERVAL 10 DAY),QuotationStatus = '处理中' Where QuotationNo='QT1808004';
    Update Quotations Set InquiryDate=DATE_ADD(DATE_ADD(curdate(),INTERVAL -day(curdate())+1 day),INTERVAL 18 DAY),QuotationStatus = '处理中' Where QuotationNo='QT1808005';

    -- 插件-未交货的S/C
    Update SalesOrders Set OrderDate=curdate(),DeliveryDate=DATE_ADD(curdate(),INTERVAL +3 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808001';
    Update SalesOrders Set OrderDate=curdate(),DeliveryDate=DATE_ADD(curdate(),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808002';
    Update SalesOrders Set OrderDate=curdate(),DeliveryDate=DATE_ADD(curdate(),INTERVAL +20 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808003';

    -- 销售业绩趋势
    -- 当月1号
    Update SalesOrders Set OrderDate=DATE_ADD(curdate(),interval -day(curdate())+1 day),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +21 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808004';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +1 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +22 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808005';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +2 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+2 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +23 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808006';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +3 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+3 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +24 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808007';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +4 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+4 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +25 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808008';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +5 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+5 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +26 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808009';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +6 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+6 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +27 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808010';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +7 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+7 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +28 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808011';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +8 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+8 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +29 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808012';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +9 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+9 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +30 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808013';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +10 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+10 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +31 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808014';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +11 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+11 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +32 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808015';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +12 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+12 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +33 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808016';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +13 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+13 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +34 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808017';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +14 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+14 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +35 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808018';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +15 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+15 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +36 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808019';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +16 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+16 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +37 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808020';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +17 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+17 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +38 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808021';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +18 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+18 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +39 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808022';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +19 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+19 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +40 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808023';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +20 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+20 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +41 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808024';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +21 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+21 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +42 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808025';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +22 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+22 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +43 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808026';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +23 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+23 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +44 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808027';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +24 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+24 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +45 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808028';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +25 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+25 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +46 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808029';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +26 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+26 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +47 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808030';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +27 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+27 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +48 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808031';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +28 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+28 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +49 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808032';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +29 DAY),EffectDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+29 day),INTERVAL +1 DAY),DeliveryDate=DATE_ADD(DATE_ADD(curdate(),interval -day(curdate())+1 day),INTERVAL +50 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808033';
    -- 当月30号

    -- 近3年业绩销售额
    -- 1月
    Update SalesOrders Set OrderDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),DeliveryDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808034';
    Update SalesOrders Set OrderDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),DeliveryDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808035';
    Update SalesOrders Set OrderDate=DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),DeliveryDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808036';
    -- 2月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808037';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808038';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808039';
    -- 3月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808040';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808041';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808042';
    -- 4月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808043';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808044';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808045';
    -- 5月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808046';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808047';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808048';
    -- 6月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808049';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808050';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808051';
    -- 7月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808052';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808053';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808054';
    -- 8月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808055';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808056';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808057';
    -- 9月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808058';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808059';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808060';
    -- 10月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808061';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808062';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808063';
    -- 11月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808064';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808065';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808066';
    -- 12月
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808067';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808068';
    Update SalesOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),DeliveryDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),INTERVAL +10 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808069';
    
    -- 近3年采购
    -- 1月
    Update PurchaseOrders Set OrderDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808034';
    Update PurchaseOrders Set OrderDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808035';
    Update PurchaseOrders Set OrderDate=DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808036';
    -- 2月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808037';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808038';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808039';
    -- 3月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808040';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808041';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808042';
    -- 4月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808043';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808044';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808045';
    -- 5月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808046';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808047';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808048';
    -- 6月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808049';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808050';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808051';
    -- 7月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808052';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808053';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808054';
    -- 8月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808055';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808056';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808057';
    -- 9月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808058';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808059';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808060';
    -- 10月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808061';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808062';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808063';
    -- 11月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808064';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808065';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808066';
    -- 12月
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808067';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808068';
    Update PurchaseOrders Set OrderDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),ShippingDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),INTERVAL +10 DAY),PurchaseOrderStatus = '已生效' Where PurchasePlanNo='SO1808069';

    -- 近3年出货
    -- 1月
    Update Shipments Set ShippingDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),ShipmentExpected=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP001';
    Update Shipments Set ShippingDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),ShipmentExpected=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP009';
    Update Shipments Set ShippingDate=DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),ShipmentExpected=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP021';
    -- 2月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP002';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP010';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP022';
    -- 3月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP003';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP025';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP024';
    -- 4月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP005';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP011';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP028';
    -- 5月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP007';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP013';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP029';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP037';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP038';
    -- 6月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP004';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP015';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP030';
    -- 7月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP006';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP026';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP031';
    -- 8月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP008';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP016';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP032';
    -- 9月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP012';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP018';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP033';
    -- 10月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP014';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP019';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP034';
    -- 11月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP017';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP020';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP035';
    -- 12月
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP023';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP027';
    Update Shipments Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),ShipmentExpected=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),INTERVAL +10 DAY),ShipmentStatus = '已出货' Where InvoiceNO='FP036';

    -- 近3年报关
    -- 1月
    Update Declarations Set ShippingDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),IvoiceDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),INTERVAL +10 DAY) Where InvoiceNO='FP001';
    Update Declarations Set ShippingDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),IvoiceDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),INTERVAL +10 DAY) Where InvoiceNO='FP009';
    Update Declarations Set ShippingDate=DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),IvoiceDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),INTERVAL +10 DAY) Where InvoiceNO='FP021';
    -- 2月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP002';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP010';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP022';
    -- 3月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP003';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP025';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP024';
    -- 4月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP005';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP011';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP028';
    -- 5月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP007';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP013';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP029';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP037';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP038';
    -- 6月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP004';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP015';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP030';
    -- 7月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP006';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP026';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP031';
    -- 8月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP008';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP016';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP032';
    -- 9月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP012';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP018';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP033';
    -- 10月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP014';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP019';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP034';
    -- 11月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP017';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP020';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP035';
    -- 12月
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP023';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP027';
    Update Declarations Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),IvoiceDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),INTERVAL +10 DAY) Where InvoiceNO='FP036';

    -- 近3年结算
    -- 1月
    Update Settlements Set ShippingDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),CheckoutDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP001';
    Update Settlements Set ShippingDate=DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),CheckoutDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP009';
    Update Settlements Set ShippingDate=DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),CheckoutDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP021';
    -- 2月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP002';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 1 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP010';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP022';
    -- 3月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP003';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 2 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP025';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP024';
    -- 4月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP005';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 3 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP011';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 3 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP028';
    -- 5月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP007';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 4 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP013';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 4 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP029';
    -- 6月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP004';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 5 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP015';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 5 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP030';
    -- 7月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP006';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 6 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP026';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 6 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP031';
    -- 8月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP008';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 7 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP016';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 7 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP038';
    -- 9月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP012';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 8 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP018';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 8 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP033';
    -- 10月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP014';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 9 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP019';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 9 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP034';
    -- 11月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP017';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 10 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP020';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 10 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP035';
    -- 12月
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 2 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP023';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 1 YEAR), INTERVAL 11 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP027';
    Update Settlements Set ShippingDate=DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),CheckoutDate=DATE_ADD(DATE_ADD(DATE_SUB(CURDATE(),INTERVAL dayofyear(now())-1 DAY), INTERVAL 11 MONTH),INTERVAL +10 DAY) ,isCheckout=1 Where InvoiceNO='FP037';

    -- 当日订单
    Update SalesOrders Set OrderDate=CURDATE(),EffectDate=CURDATE(),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808070';
    Update SalesOrders Set OrderDate=CURDATE(),EffectDate=CURDATE(),DeliveryDate=DATE_ADD(CURDATE(),INTERVAL +20 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808071';
    Update SalesOrders Set OrderDate=CURDATE(),EffectDate=CURDATE(),DeliveryDate=DATE_ADD(CURDATE(),INTERVAL +18 DAY),SalesOrderStatus = '已生效' Where SalesOrderNo='SO1808072';

    -- 跟进中的收样
    Update ReceiveSamples Set Deadline=DATE_ADD(CURDATE(),INTERVAL +3 DAY),ReceiveSampleStatus='跟进中' Where TNTNo='RS1808001';
    Update ReceiveSamples Set Deadline=DATE_ADD(CURDATE(),INTERVAL +15 DAY),ReceiveSampleStatus='跟进中' Where TNTNo='RS1808002';
    Update ReceiveSamples Set Deadline=DATE_ADD(CURDATE(),INTERVAL +20 DAY),ReceiveSampleStatus='跟进中' Where TNTNo='RS1808003';

    -- 未交货的P/0
    Update PurchaseOrders Set ShippingDate=DATE_ADD(CURDATE(),INTERVAL +3 DAY),PurchaseOrderStatus='待确认' Where PurchaseOrderNo='SO1808070-1';
    Update PurchaseOrders Set ShippingDate=DATE_ADD(CURDATE(),INTERVAL +6 DAY),PurchaseOrderStatus='已生效' Where PurchaseOrderNo='SO1808070-2';
    Update PurchaseOrders Set ShippingDate=DATE_ADD(CURDATE(),INTERVAL +15 DAY),PurchaseOrderStatus='已生效' Where PurchaseOrderNo='SO1808070-3';

    -- 跟进中的出运明细
    Update Shipments Set ShipmentExpected=DATE_ADD(CURDATE(),INTERVAL +27 DAY),ShipmentStatus='已进仓' Where InvoiceNO='FP003';

    -- 应付货款详情
    Update SettlementsDetail Set PaymentDate=DATE_ADD(CURDATE(),INTERVAL +3 DAY) Where rid='B24FD894-9E13-49AC-A78D-0AC9E165C090';
    Update SettlementsDetail Set PaymentDate=DATE_ADD(CURDATE(),INTERVAL +5 DAY) Where rid='FA7C5F12-48DF-48F1-89BC-74F5174A75C0';
    Update SettlementsDetail Set PaymentDate=DATE_ADD(CURDATE(),INTERVAL +9 DAY) Where rid='8B8457FD-A995-4218-90EF-BDB7F7C731E6';
    Update SettlementsDetail Set PaymentDate=DATE_ADD(CURDATE(),INTERVAL +13 DAY) Where rid='B111A2DA-7066-4EAB-A1BD-1A65AC03A5E1';
    Update SettlementsDetail Set PaymentDate=DATE_ADD(CURDATE(),INTERVAL +18 DAY) Where rid='FAD1EE23-06EC-4E12-B85F-1FBC9489B393';

    -- 应收货款详情
    Update Settlements Set CollectionDate=DATE_ADD(CURDATE(),INTERVAL +3 DAY) Where InvoiceNO='FP001';
    Update Settlements Set CollectionDate=DATE_ADD(CURDATE(),INTERVAL +17 DAY) Where InvoiceNO='FP002';
    Update Settlements Set CollectionDate=DATE_ADD(CURDATE(),INTERVAL +33 DAY) Where InvoiceNO='FP003';

    -- 重置本次更新时间
    Update Sys_User set mtime=CURDATE() Where rid='6b86a0b1-7f26-11e8-9636-c49ded015d02';
end $ 
delimiter ;